version: '3'

services:
  node1:
    build: ./node
    ports:
      - "5001:5000"
    networks:
      - DLT

  node2:
    build: ./node
    ports:
      - "5002:5000"
    networks:
      - DLT

  node3:
    build: ./node
    ports:
      - "5003:5000"
    networks:
      - DLT

  node4:
    build: ./node
    ports:
      - "5004:5000"
    networks:
      - DLT

  node5:
    build: ./node
    ports:
      - "5005:5000"
    networks:
      - DLT

networks:
  DLT:
    driver: bridge
